### ISSUE TITLE
Multiple compile destinations within dependency path

### ISSUE THREAD

**Issue by tmcgill** [mjvotaw/Coda-2-LESS-Compiler#23]
Here is a simplified description of what I am attempting to achieve...
My project uses three LESS files: a.less, b.less, and c.less. The contents of each look like:

== a.less ==
.aClass {...}

== b.less ==
@import "a.less"
.bClass {...}

== c.less ==
@import "b.less"
.cClass {...}

I would like to compile two css files on every save: b.css and c.css. The contents of each would be:

== b.css ==
.aClass {...}
.bClass {...}

== c.css ==
.aClass {...}
.bClass {...}
.cClass {...}

Is what I describe possible? If so, please explain how. If not, please consider this a feature request. Thanks.

**Comment by mjvotaw** [comment]
Ah, this is an interesting case. So you have two separate css files, one of which is a dependency on the other. I'll have to see what I can do about this.

**Comment by tmcgill** [comment]
Thanks. My real-world use case is that I'm compiling Bootstrap with accessibility and branding layers (this maps to b.less in my simplified example) and then adding a layer for CMS-specific styles (this maps to c.less in my simplified example). This arrangement allows me to use b.css for hand-coded projects and c.css for CMS-based projects while centrally maintaining styles for both.

**Comment by mjvotaw** [comment]
Okay, so it looks like you can sort of do this, but it depends on the order in which you add them to the Site Settings. If you add c.less first, the plugin won't let you add b.less, because it sees that it's already a dependency of c.less

But, if you add b.less first, then c.less, you can create css files for each.

The only problem with this is that saving b.less won't cause c.less to recompile, because the plugin finds the main entry for b.less first. Manually saving c.less will recompile it with changes from b.less, though.

I never really expected a situation such as this, so I'm not quite sure how to handle it.

**Comment by mjvotaw** [comment]
I promise I haven't forgotten about this, just haven't had a chance to work on this in a bit.

**Comment by tmcgill** [comment]
Oh awesome. Thanks for keeping this in mind.
T

On Jun 1, 2016, at 7:26 AM, Michael Votaw <notifications@github.com<mailto:notifications@github.com>> wrote:


I promise I haven't forgotten about this, just haven't had a chance to work on this in a bit.
