### ISSUE TITLE
Multiple Watched Less Files: first one compliles the rest do not

### ISSUE THREAD

**Issue by steveosphere** [mjvotaw/Coda-2-LESS-Compiler#25]
I see your thing.less, thing2.less, thing3.less example on the code tab. I am trying to something similar (i think) where a series of watched less files share the same base set of imports with just slight variable differences all in the same folder. When I make a change to one of the import files I was expecting all of the watched less files to compile but it is only compiling the first one. Each one below that is not compiling. Is this a bug or is there some sort of setting I don't have configured? ...or is this not the desired behavior.

**Comment by mjvotaw** [comment]
It sounds like you want a similar functionality to issue #23 (compiling multiple files when saving a common dependency)?

I hadn't really considered this as a possibility when building this plugin, and due to some design choices it's been more difficult than I'd have expected to implement this. I definitely want to add this support, I just unfortunately haven't had much time to work on this plugin lately.
